datasource:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://database-food-place-project.cvyclyh4jg14.ap-northeast-2.rds.amazonaws.com:3306/food_place_project
  jpa:
    show-sql: true

jwtpassword:
  source: ${JWT_SECRET_KEY}


oauth:
  kakao:
    client-id: d7453d5d4fe1c096ca03c1ed009a03ff
    secret: K5U5BQQ9UdpwJvlPC0lP8mWBGQxXTe85
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
      redirect-uri: http://localhost:8080/api/auth/kakao

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: false

cloud:
  aws:
    s3:
      bucket: ${BUCKET}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

#  {bucket}{access-key}{secret-key}